In [7]:
import numpy as np

In [8]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [9]:
u = np.array([2,5,7,9])

In [10]:
u

array([2, 5, 7, 9])

In [11]:
v = np.array([1,0,0,2])

In [12]:
v

array([1, 0, 0, 2])

In [13]:
u * 2

array([ 4, 10, 14, 18])

In [14]:
u + v

array([ 3,  5,  7, 11])

In [15]:
u * v

array([ 2,  0,  0, 18])

In [16]:
u.shape

(4,)

In [17]:
v.shape

(4,)

In [18]:
u.shape[0]

4

In [19]:
v.shape[0]

4

In [20]:
def vector_vector_multiplication(u,v):
    
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [21]:
vector_vector_multiplication(u,v)

np.float64(20.0)

In [22]:
U = np.array([
    [ 1 , 4 , 7 , 9 ],
    [ 2 , 5 , 8 , 5 ],
    [ 3 , 6 , 9 , 1 ]
])

In [23]:
U

array([[1, 4, 7, 9],
       [2, 5, 8, 5],
       [3, 6, 9, 1]])

In [24]:
U.shape

(3, 4)

In [25]:
U.shape[0]

3

In [54]:
U.shape[1]

4

In [60]:
v.shape[0]

4

In [62]:
U.shape

(3, 4)

In [69]:
def matrix_vector_multiplication(U,v):
    
    assert U.shape[1] == v.shape[0]

    rows_num = U.shape[0]

    result = np.zeros(rows_num)

    for i in range(rows_num):
        result[i] = vector_vector_multiplication(U[i],v)
        
    return result

In [70]:
matrix_vector_multiplication(U,v)

array([19., 12.,  5.])

In [72]:
U.dot(v)

array([19, 12,  5])

In [77]:
V = np.array([
    [9,5,1],
    [7,5,3],
    [0,0,1,],
    [8,5,2]
])

In [79]:
V

array([[9, 5, 1],
       [7, 5, 3],
       [0, 0, 1],
       [8, 5, 2]])

In [91]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    rows_num = U.shape[0]
    cols_num = V.shape[1]
    result = np.zeros((rows_num,cols_num))
    for i in range(cols_num):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    return result    

In [92]:
matrix_matrix_multiplication(U,V)

array([[109.,  70.,  38.],
       [ 93.,  60.,  35.],
       [ 77.,  50.,  32.]])

In [93]:
U.dot(V)

array([[109,  70,  38],
       [ 93,  60,  35],
       [ 77,  50,  32]])

Identity Matrix

In [95]:
I = np.eye(3)

In [96]:
V

array([[9, 5, 1],
       [7, 5, 3],
       [0, 0, 1],
       [8, 5, 2]])

In [97]:
V.dot(I)

array([[9., 5., 1.],
       [7., 5., 3.],
       [0., 0., 1.],
       [8., 5., 2.]])

Inverse Matrix

In [98]:
Vs = V[[0,1,2]]
Vs

array([[9, 5, 1],
       [7, 5, 3],
       [0, 0, 1]])

In [104]:
 Vs_inv = np.linalg.inv(Vs)

In [106]:
np.round(Vs_inv.dot(Vs), 10)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])