In [7]:
import numpy as np

In [8]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.full(5,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [16]:
a= np.array([1,3,55,75,441])
a

array([  1,   3,  55,  75, 441])

In [17]:
a[2]

np.int64(55)

In [18]:
a[2] = 10
a

array([  1,   3,  10,  75, 441])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [28]:
 # Select an element of a matrix
n[0,1] = 20

In [29]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
 # Select a row of a matrix
n[2] = [1,1,1]

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [41]:
 # Select the third cloum of the matrix
 # The : symbol means all the rows on second cloum
n[:,2] = [2,2,2]

In [36]:
n

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [40]:
# Makes a random matrix or array
np.random.rand(5,2)

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [39]:
# When you set a seed it always make the same random array evevn with different environments
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [42]:
 # This random matrix also contain '-' numbers 
np.random.randn(5,2)

array([[-0.74787095,  0.00902525],
       [-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229]])

In [44]:
 # Make random numbers between 0 and 100
100*np.random.rand(5,2)

array([[46.77874846, 20.17432263],
       [64.04067252, 48.30698356],
       [50.523672  , 38.68926511],
       [79.36374544, 58.00041789],
       [16.22985985, 70.07523466]])

In [45]:
 # Make random matrix of integer numbers
np.random.randint(low=0,high=100,size=(5,2))

array([[90, 62],
       [83, 96],
       [43, 32],
       [26,  8],
       [76, 10]])

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [49]:
a+1

array([1, 2, 3, 4, 5])

In [50]:
a*2

array([0, 2, 4, 6, 8])

In [51]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [54]:
b=(10+(a*2))**2
b

array([100, 144, 196, 256, 324])

In [55]:
a + b

array([100, 145, 198, 259, 328])

In [56]:
a>= 2

array([False, False,  True,  True,  True])

In [60]:
b>a

array([ True,  True,  True,  True,  True])

In [61]:
 # This print all the elements of the "a" array that meet the condition in bracket
a[b>a]

array([0, 1, 2, 3, 4])

In [62]:
a.min()

np.int64(0)

In [64]:
a.max()

np.int64(4)

In [65]:
a.sum()

np.int64(10)

In [68]:
 # Shows the average number
a.mean()

np.float64(2.0)

In [69]:
a.std()

np.float64(1.4142135623730951)

In [71]:
 # Sum of the matrix members
n.sum()

np.int64(38)

In [72]:
n.min()

np.int64(1)