In [1]:
import numpy as np
import pandas as pd
# Ipmopting required packages

In [2]:
np
# Test and define numpy

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
pd
# Test and define pandas

<module 'pandas' from '/home/codespace/.local/lib/python3.12/site-packages/pandas/__init__.py'>

In [4]:
pd.__version__
# Finding Pandas version

'2.3.1'

In [5]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'
# Saving data in link in 'data' variable

In [72]:
!wget $data
# Downloadfing data

--2025-09-20 03:39:19--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.2’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.03s   

2025-09-20 03:39:19 (23.9 MB/s) - ‘car_fuel_efficiency.csv.2’ saved [874188/874188]



In [74]:
df = pd.read_csv('car_fuel_efficiency.csv')
# Make a new dataframe from the 'csv' file

In [75]:
df
# Test dataframe

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [8]:
len(df)
# Calculate number of all elements in dataframe

9704

In [9]:
len(df.fuel_type.unique())
# Calculate unique fuel types in dataset

2

In [10]:
len(sum(np.where(df.isnull().sum() > 0)))
# Calculate the number of columns those contain null values

4

In [11]:
max(df[(df.origin == 'Asia')].fuel_efficiency_mpg)
# Calculating maximum fuel efficiency in Asia

23.759122836520497

In [79]:
df.horsepower.median()
# Calculate the median of horsepower 

np.float64(152.0)

In [80]:
mfh = df.horsepower.mode()
# Find the most frequent item in 'horsepower' records
# 'mfh' = Most Frequent Horsepower
mfh

0    152.0
Name: horsepower, dtype: float64

In [88]:
df.horsepower = df.horsepower.fillna(float(mfh.iloc[0]))
# Replace the 'NaN' values with the 'mfh' that we calculated before
df.horsepower.isnull().sum()
# Testing the code to make sure there isn't any 'NaN' values
df.horsepower

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [160]:
df.horsepower.median()
# Calculate the median agian to define the changes

np.float64(152.0)

In [123]:
asia_df = df[(df.origin == 'Asia')]
# Make new Dataframe just with Asia origin cars
asia_df.reset_index(drop=True, inplace=True)
# Reset the index for sort 

In [151]:
X = asia_df.loc[0:6, ['vehicle_weight', 'model_year']]
# Select first seven records of 'vehicle_weight' and 'model_year' and call them 'X'
X = X.to_numpy()
# Trun 'X' from a  Pandas Dataframe to an Numpy array
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [152]:
XTX = X.T.dot(X)
# Calculate multiplication between 'X' and its transpose is 'X.T'
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [153]:
XTX_inv = np.linalg.inv(XTX)
# Inverting the 'XTX' array
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [154]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
# Define the 'y' array

In [158]:
w = XTX_inv.dot(X.T).dot(y)
# Claculate the 'w'
w

array([0.01386421, 0.5049067 ])

In [159]:
sum(w)

np.float64(0.5187709081074016)